alumno_tabla:
    path:     /alumno/all
    defaults: { _controller: GestorFCTBundle:Alumno:mostrarAlumno }

login:
    path:     /login
    defaults: { _controller: GestorFCTBundle:Registration:login }

registrarse:
    path:     /registrarse
    defaults: { _controller: GestorFCTBundle:Registration:register }

admin:
    path:     /admin
    defaults: { _controller: GestorFCTBundle:Registration:admin }





profesor_tabla:
    path:     /profesor/all
    defaults: { _controller: GestorFCTBundle:Profesor:mostrarProfesor }

profesor_form:
    path:     /profesor/new
    defaults: { _controller: GestorFCTBundle:Profesor:formularioProfesor }

profesor_api:
    path:     /profesor/api
    defaults: { _controller: GestorFCTBundle:Profesor:proferosesApi }
    methods: [GET]


empresa_tabla:
    path:     /empresa/all
    defaults: { _controller: GestorFCTBundle:Empresa:mostrarTabla }

empresa_form:
    path:     /empresa/new
    defaults: { _controller: GestorFCTBundle:Empresa:formulario }

empresa_api:
    path:     /empresas/api
    defaults: { _controller: GestorFCTBundle:Empresa:empresas }
    methods: [GET]
