app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

gestor_fct:
    resource: "@GestorFCTBundle/Resources/config/routing.yml"
    prefix:   /gestor/

logout:
    path: /gestor/logout
