# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
      GestorFCTBundle\Entity\User: bcrypt
      Symfony\Component\Security\Core\User\User: plaintext

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
      db_provider:
          entity:
            class: GestorFCTBundle:User



    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        usuario:
          pattern: ^/gestor
          anonymous: ~
          provider: db_provider
          provider: in_memory
          form_login:
              login_path: /gestor/login
              check_path: /gestor/login
          logout:
            path: /gestor/logout
            target: /gestor/login
          remember_me:
            secret:   '%secret%'
            lifetime: 604800 # 1 week in seconds
            path:     /gestor/login

        main:
            anonymous: ~

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        - { path: ^/gestor/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/gestor/registrarse, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/gestor/admin, roles: ROLE_ADMIN }
        - { path: ^/gestor, roles: ROLE_USUARIO }
